### ISSUE TITLE
pol2CartTaylor Bug

### ISSUE THREAD

**Issue by JonGallagher** [USNavalResearchLaboratory/TrackerComponentLibrary#10]
In pol2CartTaylor.m:

line 108: RCart(2,1,curPoint)=RCart(1,2);
should be RCart(2,1,curPoint)=RCart(1,2,curPoint);

Great library and resource! Thanks!

**Comment by DavidFCrouse** [comment]
The correction was added along with similar corrections in other parts of the file.
