### ISSUE TITLE
error in randPointInEllipsoid.m

### ISSUE THREAD

**Issue by J-S-Robinson** [USNavalResearchLaboratory/TrackerComponentLibrary#11]
Hello,

Thanks for having this resource available, it's been a big help for me.

For algorithm 0 in randPointInEllipsoid.m, the min and max bounds for the random variable should be the **square root** of the diagonal of inv(invS/gamma), so lines 77-78 should be:

        minBounds=-sqrt(diag(S));
        maxBounds=sqrt(diag(S));

as it is now, the ellipse will get clipped if the covariance of the innovation is < 1.0 for any of the terms.

I checked the Sun and Farooq paper to confirm.

**Comment by DavidFCrouse** [comment]
The square root operation has been added as suggested, which corrects the bug.
