### ISSUE TITLE
Error in function makeStandardCartOnlyLRMatHyps

### ISSUE THREAD

**Issue by csnje** [USNavalResearchLaboratory/TrackerComponentLibrary#12]
Fantastic library of functionality. Thank you for publishing.

In the function `makeStandardCartOnlyLRMatHyps` [Assignment Algorithms/2D Cost Matrix Formation/makeStandardCartOnlyLRMatHyps.m], I'm curious if there is an error on the Mahalanobis distance calculation inside the measurement loop (line 237):
```
Pzz=PzPred+(SRCart(:,:,curMeas)*SRCart(:,:,curMeas))';
```
Should this instead be (note shift in matrix transpose operator):
```
Pzz=PzPred+(SRCart(:,:,curMeas)*SRCart(:,:,curMeas)');
```

**Comment by DavidFCrouse** [comment]
Thanks. The bug has been fixed.
