### ISSUE TITLE
`geogHeading2ENUVec` heading not from North

### ISSUE THREAD

**Issue by mgrutten** [USNavalResearchLaboratory/TrackerComponentLibrary#14]
The `geogHeading2ENUVec` function calculates a vector assuming a heading anti-clockwise from East, not clockwise from North (as specified in the documentation).

At the moment lines 39-41 look like
```
u=[cos(heading).*cosEl;
   sin(heading).*cosEl;
   sinEl];
```
and I believe they should be
```
u=[sin(heading).*cosEl;
   cos(heading).*cosEl;
   sinEl];
```
in order to match the documentation.

I noticed the problem when using the `makeConstSpeedLevelCurvedEarthTraj` function, which is producing velocities that aren't consistent with the rate-of-change of position.

**Comment by DavidFCrouse** [comment]
Thanks. The correction has been pushed.
