### ISSUE TITLE
Algorithm selection in `singleScanUpdateWithExistence`

### ISSUE THREAD

**Issue by mgrutten** [USNavalResearchLaboratory/TrackerComponentLibrary#15]
I think that there's a mismatch between the algorithm description (in the function help) and the implementation.
It looks like `algSel`=0 is JIPDA and `algSel`=1 is GNN-JIPDA.  Line 227 has
```matlab
if(algSel1==1||algSel1==3)%If a GNN estimate is used in place of the mean
```
which I think should be
```matlab
if(algSel1==0||algSel1==3)%If a GNN estimate is used in place of the mean
```
to match the documentation?

**Comment by DavidFCrouse** [comment]
Thanks. The correction has been pushed.
