### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by dinglei282919** [USNavalResearchLaboratory/TrackerComponentLibrary#17]
![bug](https://user-images.githubusercontent.com/115928379/221356375-c746a889-39dd-4341-883a-c9aab4fbcf36.png)
After I install the compiler，I still fail to run CompileCLibraries function in order to compile C/C++ code. What I use is matlab 2021b and Corresponding compiler,so I don't know what the problem is. I really hope someone can answer my question!

**Comment by DavidFCrouse** [comment]
This appears to be due to a compiler that strictly enforces "static" declarations of functions. The functions in lbfgs.c shouldn't have been declared static (since they are also declared in the header). This has been corrected.

**Comment by dinglei282919** [comment]
Dear sir.
&nbsp;I'm sorry to bother you. This is my first contact with multi-target tracking algorithm,&nbsp;so I don't know many concepts very well.&nbsp;When I run the sample code 'demo2DIntegratedDataAssociation.m',&nbsp;code can only run when&nbsp;algSel1=3 or 4 or 6. However，in the file 'singleScanUpdateWithExistence.m', I found that the value of algSel1&nbsp;can be 0 to 6. I really want to konw why the code can't run when algSel1=0 or 1 or 2 or 5.
I would appreciate it if you could answer my doubts in your busy schedule.&nbsp;
Best wishes，
Lei Ding




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "David F. ***@***.***&gt;; 
发送时间: 2023年2月27日(星期一) 晚上11:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [USNavalResearchLaboratory/TrackerComponentLibrary] Unable to compile (Issue #17)





 
This appears to be due to a compiler that strictly enforces "static" declarations of functions. The functions in lbfgs.c shouldn't have been declared static (since they are also declared in the header). This has been corrected.
