### ISSUE TITLE
Questions about sample code

### ISSUE THREAD

**Issue by dinglei282919** [USNavalResearchLaboratory/TrackerComponentLibrary#18]
This is my first contact with multi-target tracking algorithm, so I don't know many concepts very well. When I run the sample code 'demo2DIntegratedDataAssociation.m', code can only run when algSel1=3 or 4 or 6. However，in the file 'singleScanUpdateWithExistence.m', I found that the value of algSel1 can be 0 to 6. I really want to konw why the code can't run when algSel1=0 or 1 or 2 or 5. Another problem is how to extend the example 'demo2DIntegratedDataAssociation.m' to three-dimensional situation，I hope to get some suggestions.

**Comment by DavidFCrouse** [comment]
Regarding the question about algorithm selection in singleScanUpdateWithExistence, the example code was written as a minimal example tailored for algorithms 3, 4, and 6.

The example is a 2D example. However, most of the functions called are not specialized for use in scenarios with any particular dimensionality.
