### ISSUE TITLE
Az/el differences

### ISSUE THREAD

**Issue by mgrutten** [USNavalResearchLaboratory/TrackerComponentLibrary#19]
Which library function can I use to calculate the az/el differences between two pairs of spherical coordinates (in az/el)?  I'm sure it's in the library somewhere, but I haven't found it.

I'd like to account for the case where the elevation is flipped.  For example, for a pair of (az, el) coordinates (45, 89), (-135, 89) I'd like the difference to be (0, 2), not (180, 0)?

**Comment by DavidFCrouse** [comment]
Use spher2Cart to convert them into Cartesian unit vectors  and then use angBetweenVecs function. The inputs and outputs of the functions in the library are in radians, so if you want degrees it is rad2deg(angBetweenVecs(spher2Cart(deg2rad([45;89])),spher2Cart(deg2rad([-135;89])))) .

**Comment by mgrutten** [comment]
Apologies, I should have chosen a better example.
I'm not after the angular distance, I would like az and el differences.  They're the same in the (poor) example I used, but not in general.
