### ISSUE TITLE
magHeading2Geog.m uses a SystemType  error that is rejected by spherHarmonicEval.m

### ISSUE THREAD

**Issue by apohelion** [USNavalResearchLaboratory/TrackerComponentLibrary#20]
**The Problem**
The function **magHeading2Geog.m** fails at line 105 

_[~,gradV]=spherHarmonicEval(C,S,ellips2Sphere(points,a,f),aH,cH,true);_

This problem is caused by the assigned values, 'true', for the 6 input argument, SystemType, in **spherHarmonicEval.m**, which only accepts two values, 0 and 2. This error prevents the unit test in **magHeading2Geog.m** form returning the desired value of 0.

**Solution**
Suggest that the 6th input arguement is removed from line 105 in **magHeading2Geog.m**.  i.e.

_[~,gradV]=spherHarmonicEval(C,S,ellips2Sphere(points,a,f),aH,cH);_

This will align **magHeading2Geog.m** with the implementation in **geogHeading2Mag.m** at line 110

This change allows the unit test in **geogHeading2Mag.m** to run correctly.

**Comment by DavidFCrouse** [comment]
The fix has been incorporated and pushed.
