### ISSUE TITLE
Matlab 2D Assignment initialises the pred variable to wrong size

### ISSUE THREAD

**Issue by cJR-McPyro** [USNavalResearchLaboratory/TrackerComponentLibrary#21]
assign2D.m and assign2DFull.m initialize the pred variable as:

`pred=zeros(numCol,1);`

With problems where numRow > numCol, it can be index as :

`pred(curRow)=curCol;`

This causes the pred variable's size to grow dynamically as more rows are evaluated, causing a potential hit to performance (particularly where numRow is much bigger than numCol.

To avoid the repeated potential reallocations, pred should be initialized as:

`pred=zeros(numRow,1);`

The C implementation initializes memory for pred to be be numRows in length.

NOTE: I haven't examined whether the other variants of 2D assignment need a similar change.

**Comment by DavidFCrouse** [comment]
Thanks. The issue in those files and in an additional file has been fixed and pushed to the repository.
