### ISSUE TITLE
Incorrect answer for murty-1968 example

### ISSUE THREAD

**Issue by kappa2k** [USNavalResearchLaboratory/TrackerComponentLibrary#4]
Running kBest2DAssign function on the example in murty-1968's paper, return incorrect answer:
>> cost_mat = [
        7 51 52 87 38 60 74 66 0 20
        50 12 0 64 8 53 0 46 76 42
        27 77 0 18 22 48 44 13 0 57
        62 0 3 8 5 6 14 0 26 39
        0 97 0 5 13 0 41 31 62 48
        79 68 0 0 15 12 17 47 35 43
        76 99 48 27 34 0 0 0 28 0
        0 20 9 27 46 15 84 19 3 24
        56 10 45 39 0 93 67 79 19 38 
        27 0 39 53 46 24 69 46 23 1];
>> [a, b, c] = kBest2DAssign(cost_mat, 1);
>> [a'; b'] , c
ans =
     9     7     3     8     6     4    10     1     5     2
     8    10     3     6     9     5     2     4     1     7
c =
     0

which is obviously incorrect

**Comment by DavidFCrouse** [comment]
Actually, the result is correct. It looks like you are misinterpreting the col4row and row4col outputs (your a and b). To demonstrate this, I modify your example:
cost_mat = [7   51  52  87  38  60  74  66  0   20;
                    50  12  0   64  8   53  0   46  76  42;
                    27  77  0   18  22  48  44  13  0   57;
                    62  0   3   8   5   6   14  0   26  39;
                    0  97  0   5   13  0   41  31  62  48;
                    79  68  0   0   15  12  17  47  35  43;
                    76  99  48  27  34  0   0   0   28  0;
                    0  20  9   27  46  15  84  19  3   24;
                   56  10  45  39  0   93  67  79  19  38;
                   27  0   39  53  46  24  69  46  23  1];
[col4row, row4col, c]=kBest2DAssign(cost_mat,1);
N=size(cost_mat,1);%It is a square matrix.

tuples=zeros(2,N);
for curRow=1:N
    tuples(1,curRow)=curRow;
    tuples(2,curRow)=col4row(curRow);
end

tuples
c

cVerify=0;
for curRow=1:N
    cVerify=cVerify+cost_mat(curRow,col4row(curRow));
end
cVerify

cVerify=0;
for curCol=1:N
    cVerify=cVerify+cost_mat(row4col(curCol),curCol);
end
cVerify

The output is:
tuples =
     1     2     3     4     5     6     7     8     9    10
     9     7     3     8     6     4    10     1     5     2
c =
     0
cVerify =
     0
cVerify =
     0

In Murty's paper entitled "An Algorithm for ranking all the assignments in order of increasing cost", in the example given, it notes that the optimal cost is indeed 0, which c is as well as cVerify obtained using both of the assignment outputs. However, you were not correctly building the tuples, as I did above. You will note that the tuples now match exactly what is in Murty's paper.
