### ISSUE TITLE
Trouble with compiling (CompileCLibraries.m) on Linux 14.04

### ISSUE THREAD

**Issue by PeterZhel** [USNavalResearchLaboratory/TrackerComponentLibrary#7]
First, I would like to thank all of you.

The issue is:
![image](https://user-images.githubusercontent.com/9888026/46020633-7d7b2180-c0e7-11e8-9183-8f98c0be2417.png)

Is there another way to make static lib or probably another answer. I am using MATLAB 2017.
Thanks a lot!

**Comment by DavidFCrouse** [comment]
The function CompileCLibraries.m has been modified so that -fPIC was included. I reproduced the problem under Centos and this fixed it.
