### ISSUE TITLE
UTC2YearFrac.m Bug

### ISSUE THREAD

**Issue by nhz2** [USNavalResearchLaboratory/TrackerComponentLibrary#9]
There is a small bug in `UTC2YearFrac.m`

## Example Reproducing The Bug
Running `[year,dayCount,second]=UTC2DayCount(2444605,0)`
gives

```
>> [year,dayCount,second]=UTC2DayCount(2444605,0)

year =

        1980


dayCount =

   366


second =

       43200
```
So clearly Julian date 2444605 is in year 1980; however, running `UTC2YearFrac(2444605,0)`
gives

```
>> UTC2YearFrac(2444605,0)

ans =

          1981.00136612022
```
This doesn't make any sense, because the decimal year should be less than 1981 if the year is less than 1981.

## Fix

Change line 51 of `UTC2YearFrac.m` 

Original: `secOfYear=second+dayCount*24*60*60+leapSecs;`
Fixed: `secOfYear=second+(dayCount-1)*24*60*60+leapSecs;`

This fixes the bug because according to the documentation of `UTC2DayCount.m` line 17, "Values in dayCount are integers >=1".

**Comment by DavidFCrouse** [comment]
The suggested fix has been incorporated.
